#pragma once

#define DSHOT_BIDIR			TRUE
#define DSHOT_SPEED			300
#define DSHOT_CHANNELS			4
#define DSHOT_AT_LEAST_ONE_32B_TIMER    FALSE
#define DSHOT_BIDIR_EXTENTED_TELEMETRY	TRUE
#define DSHOT_STATISTICS		FALSE


